### ISSUE TITLE
Background of Toolbar is Light Grey on Mac OS X (Yosemite)

### ISSUE THREAD

**Issue by tmack8001** [nvtkaszpir/mumble-skin-gray#1] opened 2015-02-20 05:08 UTC
See the below screen shot of what I'm talking about, everything else looks great!

![mumble -- 1 2 8](https://cloud.githubusercontent.com/assets/2158627/6281732/55997266-b87b-11e4-88fa-c8d0eadd2fdc.jpg)

**Comment by nvtkaszpir** [comment] 2015-02-20 07:25
Sorry I don't have a mac with a new operating system (I got only old mbp with AFAIR OSX 10.6 and I use it extremely rarely), so I cannot reproduce it yet with new OSX.
Also, knowing Apple products I got a feeling this may be hard to fix.

Did you test other skins?
Also please test if other Window Styles  except Plastique change anything.

**Comment by tmack8001** [comment] 2015-02-20 22:20
I figured you wrote this skin for a Windows machine, just wanted to point out any potential issues with the MacOS (I know how difficult Macs are sometimes).

I haven't tested other skins, just got my mumble server setup again.

**Comment by nvtkaszpir** [comment] 2019-01-02 11:38
won't fix.

**Closed as completed** 2019-01-02 11:38 UTC
